### ISSUE TITLE
It looks like a Clickup site change has broken the scraping in the plugin.

### ISSUE THREAD

**Issue by alldayalone** [alldayalone/clickup-copy-link#1]
Hi,

It looks like a Clickup site change has broken the scraping in the plugin.

To fix:

   function getSingleTaskDetails() {
-    const title = document.querySelector(".task-name__overlay").textContent;
+    const title = document.querySelector(".cu-task-title__overlay").textContent;
     const [id] = location.pathname.split('/').reverse();
     const link = location.href;

It works fine after that.

Cheers,
Casey

**Comment by alldayalone** [comment]
It works fine for my version of ClickUp 🤔 

I think i'm just going to combine those selectors to support both worlds.
<img width="1440" alt="image" src="https://github.com/alldayalone/clickup-copy-link/assets/32430949/37e63f2b-689f-49e3-ac4a-447094835ba4">

**Comment by bartoncasey** [comment]
Are you on version 3.0 of the site? It may be a new layout.

![image](https://github.com/alldayalone/clickup-copy-link/assets/3731478/3ff3a857-93fd-410b-a308-91e31ae5fc63)
